_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  # WEIGHTS: "./weights/TN_FPN_adain.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (10000, 20000)
  FACTOR_LIST: (1, 1, 1)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("HS50_train", )
  TRAIN_LABEL: ("HS50_train", "H60_train", "TN_train")
  TRAIN_UNLABEL: ("H60_train",)
  TEST: ("HS50_test", "H60_test", "TN_test", "XY_train")
  # TEST: ("TN_test",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 30000  # 有监督迭代次数   
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  CONT_CONS_LOSS_WEIGHT: 0.1
  INS_CONS_LOSS_WEIGHT: 0.1
  DIS_LOSS_WEIGHT: 0.1
  DIS_TYPE: "p6" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 3000
OUTPUT_DIR: ./output/HS50H60TN



