_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "./output/TN->H60_FPN_no_dis/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (240000, 320000, 360000, 1440000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("TN_train",)
  TRAIN_LABEL: ("TN_train",) 
  TRAIN_UNLABEL: ("H60_train",)
  TEST: ("HS50_test","H60_test","TN_test","BN_test")
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 1  # 有监督迭代次数   
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "p6" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 4000
OUTPUT_DIR: ./output/TN->H60_FPN_no_dis_1



# gen:
#   dim: 64                     # number of filters in the bottommost layer
#   mlp_dim: 256                # number of filters in MLP
#   style_dim: 8                # length of style code
#   n_downsample: 2             # number of downsampling layers in content encoder
#   n_res: 4                    # number of residual blocks in content encoder/decoder
#   activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
#   pad_type: reflect           # padding type [zero/reflect]
